### ISSUE TITLE
How to use --enumerate option of solve_max_clique

### ISSUE THREAD

**Issue by s10z** [ciaranm/parasols#1]
Hi, as I try to enumerate all cliques having a minimum size I ask myself how to tell the solver to do so. The --enumerate option looks promising though I do not understand the hint given in the --help. It might be worth to add a note in the README or to improve the options description to clarify its usage.

**Comment by ciaranm** [comment]
Ah, --enumerate doesn't quite give you that: if you combine it with an --initial-bound of one lower than the maximum clique size, it will enumerate every maximum clique. Do you need to enumerate every clique of at least a particular size, or every maximal clique of at least a particular size, or every maximum clique?

**Comment by s10z** [comment]
I need to enumerate every maximal clique of at least a particular size. So far I am using cliquer (oesgard based c++ impl) to do so.

**Comment by ciaranm** [comment]
This is a bit of a tricky problem, and as far as I know not one that's been widely studied. Using either cliquer or this code can find you cliques over a certain size, but doesn't guarantee that they're maximal: for example, if you're looking for cliques of size at least 6, and a clique of size 7 exists, then some of its six vertex subgraphs will also be listed. The Bron-Kerbosch family of algorithms, on the other hand, will give you only maximal cliques, but they don't include size based filtering so if you're looking for large cliques they're not very good.

**Comment by s10z** [comment]
Uh, this is good to know. Thanks for the hint!

I started with the BK for simplicity and were looking for different solutions as I started to test larger graphs (500 vertices, dense) and  struggled with the runtimes. I suspected already during the last week that I will have to make a conceptual switch here as the candidate counts are far too high for post processing when I just include (maximum-1)-sized cliques. It even might be the case for all maximum ones. 

In case I will go down the road at least for verification purposes to empirically test the cutoff -- is it possible to tell your code to list all maximum cliques or do I have to rely on the cliquer for that? Do you know other (faster) implementations providing an answer?

**Comment by ciaranm** [comment]
You can get all maximum cliques as follows: find the size of the maximum clique (call this w), and then rerun the program with --initial-bound w-1 --enumerate . As far as I know, this is the fastest way of doing it, at least for fairly dense graphs.

**Comment by s10z** [comment]
This is how I started. But it felt like either I did not get it going correctly or I do not understand the output. That's why I started the issue believing I might be not the only one in time interested in it ;)

I am executing my latest test on this sample file which describes a graph of 276 vertices and 29458 edges: [dimacs.txt](https://github.com/ciaranm/parasols/files/775056/dimacs.txt)

When I run `$solve_max_clique ccod dynex dimacs.txt ` I will receive 
> 17 4658
> 8 22 30 42 70 82 94 111 117 131 151 154 158 179 251 259 270 
> 10

I interprete this as the maximum clique will be formed by 17 vertices and the vertices at the indexes 8,22,30,..,270 form such a maximum clique. As I continue with 
`$solve_max_clique --initial-bound=16 --enumerate ccod dynex dimacs.txt` I will receive 
> 17 1741 5738
> 3 22 30 42 70 82 94 117 131 151 154 158 171 179 191 255 268 
> 16

which might be some other maximum clique. Using cliquer with  `$cl -q -a -m 17 dimacs.txt > out.txt` results in 5738 lines where each line is expected to remark a maximum clique. This matches with one figure of parasols output I therefore suspect to remark the total count. 

As mention in parasols  `--help` I tried it with `--print-incumbents`:
`$solve_max_clique --initial-bound=16 --enumerate --print-incumbents ccod dynex dimacs.txt`
This resulted in massive output whereas it seems to be some internal representation rather than useful vertex indexes or something:
> [...]
> -- 61 found 17 at 7 1 1 1 1 1 1 5 1 1 1 1 1 3 1 2 9
> -- 61 found 17 at 7 1 1 1 1 1 1 5 1 1 1 1 1 3 1 2 10
> -- 61 found 17 at 7 1 1 1 1 1 1 5 1 1 1 1 1 3 1 2 11
> -- 61 found 17 at 7 1 1 1 1 1 1 5 1 1 1 1 1 3 1 2 12
> -- 61 found 17 at 7 1 1 1 1 1 1 5 1 1 1 1 1 3 1 2 13
> -- 61 found 17 at 7 1 1 1 1 1 1 5 1 1 1 1 1 3 1 2 14
> 17 1741 5738
> 3 22 30 42 70 82 94 117 131 151 154 158 171 179 191 255 268 
> 61

How to receive a listing of each vertex set forming a maximum clique? Like given by cliquer? Can you provide a full sample command with all parameters I need? What am I doing wrong?

**Comment by ciaranm** [comment]
Ah, yes, the 5738 you see in the last place on the first line is the number, and the print incumbents output shows you the position, rather than the vertex numbering. I don't believe anyone has actually wanted to know what all the maximum cliques are previously (the people who wanted that option just needed a count), so I wasn't outputting that. I've changed it to give you the information you need, so that last command you ran will now be right.
